/**
 * shots.mjs — render the store imagery out of the real game.
 *
 *   node shots.mjs            every shot, into store/screenshots/
 *   node shots.mjs menu       only shots whose id contains "menu"
 *
 * Drives an unmodified index.html in headless Chrome over the DevTools protocol
 * and writes PNGs at exact pixel sizes. index.html is never copied or patched:
 * the script reaches in through window.__wiredDev, so a screenshot cannot drift
 * from what a player actually sees.
 *
 * What makes this different from photographing a hand-played board: every
 * in-game position here comes from __wiredDev.ui.stageSolution(), which replays
 * a solution the solver PROVED and stops partway. So the marketing images carry
 * the same guarantee the game does — nothing staged, nothing faked, no position
 * that a player could not have reached by the rules. They also survive a UI
 * change, because nothing here knows a pixel coordinate.
 *
 * Node 24 ships a global WebSocket, so this needs no dependencies.
 */

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { CDP, launch, sleep } from "./chrome.mjs";

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const GAME = pathToFileURL(path.join(ROOT, "index.html")).href;
const OUT = path.join(ROOT, "store", "screenshots");

/* ------------------------------- ingredients ------------------------------ */

// The intro is a one-shot splash on first load. Every shot starts past it.
// A fitted shot never goes below this, so a failed measurement cannot produce
// a sliver of an image.
const MIN_FIT = 320;

const SKIP_INTRO = `document.getElementById('introScreen').classList.add('hidden');`;

// A 6x6, three-pair board with two components, a gate and a patrol. Fixed so
// the editor shot is reproducible; regenerate with __wiredDev.encodeLevel if
// the codec version ever changes, and re-check it still solves.
const DEMO_BOARD =
  "VzF-Nn42fmEuLi4uQS4uLi4uLmMuLi4uQy4uIyMuLi4uLi4uLmIuLi4uQn5HMiwxOjEwOjQ6MH5QMjoxLDQ6NCw0";

/**
 * Stage a level partway through its proven solution.
 *
 * `at` is a fraction of the schedule, not a tick count: pars differ per level,
 * and a fixed count that reads well on Logic Array is most of the way through
 * Breadboard. Fractions keep a shot meaning "about two thirds in" no matter
 * which board it lands on.
 */
const play = (slug, at) => SKIP_INTRO + `
  const d = window.__wiredDev;
  const lv = d.LEVELS.find(l => l.slug === ${JSON.stringify(slug)});
  if (!lv) throw new Error("no level " + ${JSON.stringify(slug)});
  const sol = d.solveLevel(lv);
  d.ui.enterLevel(lv);
  const r = d.ui.stageSolution(lv, sol, Math.round(sol.actions.length * ${at}));
  d.ui.updateHud();
  // The real tick, not 0 — the sparks are wherever the staged run left them,
  // and drawing at tick 0 would put every hazard back at the start of its loop.
  d.ui.draw(r.ticks, 0);
`;

const SHOTS = [
  {
    id: "01-mid-run",
    file: "01-mid-run.png",
    width: 720, height: 900,
    // Logic Array: the densest shipped board, and the one that shows the whole
    // vocabulary at once — energised wire, the dotted route still to fill,
    // components, a gate mid-cycle and a spark on its outlined danger cell.
    // Two thirds in, so several wires are done and one is visibly still filling.
    setup: play("logic-array", 0.66),
    wait: 300,
  },
  {
    id: "02-menu",
    file: "02-menu.png",
    width: 720, height: 900,
    // The level list has to show all ten boards, the daily with its streak and
    // the per-level gold targets — at 900 tall it cuts off at Backplane. `fit`
    // measures the rendered page instead of hardcoding a taller number, so an
    // eleventh level lengthens the shot rather than getting cropped out of it.
    fit: true,
    setup: SKIP_INTRO + `window.__wiredDev.ui.showMenu();`,
    wait: 300,
  },
  {
    id: "03-settings",
    file: "03-settings.png",
    width: 720, height: 900,
    setup: SKIP_INTRO + `window.__wiredDev.ui.showSettings();`,
    wait: 300,
  },
  {
    id: "04-editor",
    file: "04-editor.png",
    width: 720, height: 900,
    fit: true,
    // The differentiator, so it has to show the green verdict rather than an
    // empty grid. Loaded through the real paste-a-code path — the same one a
    // player uses — so the shot exercises the feature instead of posing as it.
    //
    // The code is fixed rather than generated by the editor's Random button,
    // which seeds off Date.now() and would make this capture different every
    // run. It decodes to a 6x6, three-pair board the solver proves at par 20.
    setup: SKIP_INTRO + `
      window.__wiredDev.ui.showEditor();
      document.getElementById('editorImport').value = ${JSON.stringify(DEMO_BOARD)};
      document.getElementById('editorLoad').click();
      document.getElementById('editorVerify').click();
      await new Promise(r => setTimeout(r, 500));
    `,
    wait: 400,
  },
  {
    id: "05-board-sealed",
    file: "05-board-sealed.png",
    width: 720, height: 900,
    fit: true,
    // The one position stageSolution cannot produce: solutions are correct by
    // construction, and this needs a MISTAKE. The route lives in index.html as
    // SEAL_DEMO and is shared with the suite, which asserts that it really does
    // seal and that the warning names the stranded pair — so this picture
    // cannot end up advertising a warning the tests no longer prove.
    setup: SKIP_INTRO + `
      const d = window.__wiredDev;
      const r = d.ui.stageSealDemo();
      if (!r.sealed) throw new Error("the demo route did not seal: " + JSON.stringify(r));
      d.ui.updateHud();
      d.ui.draw(r.ticks, 0);
    `,
    wait: 300,
  },
  {
    id: "cover",
    file: "cover.png",
    // itch's cover slot is 630x500; captured at 2x so it stays sharp on
    // high-DPI screens, which is what store/README.md asks for.
    //
    // The viewport is the art's OWN size and the 2x comes from `scale`. A
    // standalone SVG renders at its width/height attributes and is NOT
    // stretched to the window, so asking for a 1260x1000 viewport produced a
    // 1260x1000 PNG with the art in the top-left corner and three quarters of
    // it blank white. Byte-reproducibly blank, which is why it survived a
    // determinism check: reproducibility is not correctness.
    url: pathToFileURL(path.join(ROOT, "store", "cover.svg")).href,
    width: 630, height: 500, scale: 2,
    setup: "",
    wait: 200,
  },
];

/* --------------------------------- capture -------------------------------- */

// Dead Short pulses and flashes on infinite CSS loops. Left running, a capture
// samples them at whatever phase the clock happened to be in and no two runs
// match — so pin the looping ones and hold them at t=0.
const PIN_ANIMATIONS = `(async () => {
  for (const a of document.getAnimations()) {
    // pause() BEFORE assigning currentTime. Setting the time on a running
    // animation and pausing afterwards leaves the hold time wherever the clock
    // reached, which is a frame of drift.
    if (a.effect?.getTiming?.().iterations === Infinity) {
      a.pause();
      a.currentTime = 0;
    }
  }
  // Pausing is not the same as the compositor having drawn the paused frame.
  // Two rAFs so the held phase is what actually rasterises.
  await new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r)));
})()`;

async function main() {
  const filter = process.argv[2];
  const shots = filter ? SHOTS.filter((s) => s.id.includes(filter)) : SHOTS;
  if (!shots.length) {
    console.error(`No shot id matches "${filter}". Known: ${SHOTS.map((s) => s.id).join(", ")}`);
    process.exit(1);
  }

  await mkdir(OUT, { recursive: true });
  const { cdp, sessionId, dispose } = await launch();
  const problems = [];

  try {
    for (const shot of shots) {
      const dpr = shot.scale ?? 1;
      await cdp.send("Emulation.setDeviceMetricsOverride",
        { width: shot.width, height: shot.height, deviceScaleFactor: dpr, mobile: false }, sessionId);
      await cdp.send("Emulation.setTouchEmulationEnabled",
        { enabled: !!shot.touch, maxTouchPoints: shot.touch ? 5 : 1 }, sessionId);

      // Reload each time so no shot inherits the last one's state.
      const loaded = cdp.once("Page.loadEventFired");
      await cdp.send("Page.navigate", { url: shot.url ?? GAME }, sessionId);
      await loaded;
      await sleep(250);

      const res = await cdp.send("Runtime.evaluate", {
        expression: `(async () => { ${shot.setup} })()`,
        awaitPromise: true, returnByValue: true,
      }, sessionId);
      if (res.exceptionDetails) {
        const d = res.exceptionDetails;
        problems.push(`${shot.id}: ${d.text} ${d.exception?.description ?? ""}`);
        continue;
      }

      await sleep(shot.wait ?? 300);

      // Grow the viewport to whatever the page actually needs. Two passes:
      // making the window taller can reflow content shorter (a scrollbar goes
      // away), and settling once is the difference between a crop and a fit.
      if (shot.fit) {
        let height = shot.height;
        for (let pass = 0; pass < 2; pass++) {
          // Measure the furthest-down visible element, NOT scrollHeight: body
          // carries a min-height, so scrollHeight can never report less than
          // the viewport and a shot can only ever grow. The editor page is
          // shorter than 900 and was padding the bottom third with dead space.
          const { result } = await cdp.send("Runtime.evaluate", {
            expression: `(() => {
              // Skip elements at least as tall as the window: those are layout
              // shells carrying a 100vh min-height, and measuring them just
              // hands back the viewport again — which is what made scrollHeight
              // useless here. Their children are still measured.
              const vh = window.innerHeight;
              let bottom = 0;
              for (const el of document.body.querySelectorAll('*')) {
                const r = el.getBoundingClientRect();
                if (r.width > 0 && r.height > 0 && r.height < vh) {
                  bottom = Math.max(bottom, r.bottom);
                }
              }
              const pad = parseFloat(getComputedStyle(document.body).paddingBottom) || 0;
              return Math.ceil(bottom + pad);
            })()`,
            returnByValue: true,
          }, sessionId);
          const want = Math.max(MIN_FIT, result.value);
          if (want === height && pass > 0) break;
          height = want;
          await cdp.send("Emulation.setDeviceMetricsOverride",
            { width: shot.width, height, deviceScaleFactor: dpr, mobile: false }, sessionId);
          await sleep(120);
        }
        shot.measured = height;
      }

      await cdp.send("Runtime.evaluate",
        { expression: PIN_ANIMATIONS, awaitPromise: true }, sessionId);
      await sleep(80);

      // A shot is only worth what the page actually painted. The cover shipped
      // three quarters blank and every existing check passed it, because blank
      // is perfectly deterministic — so reproducibility proved nothing here.
      // Measure instead: the root element has to cover the viewport it is shot
      // in, or the difference is page background that nobody drew.
      const { result: cov } = await cdp.send("Runtime.evaluate", {
        expression: `(() => {
          const r = document.documentElement.getBoundingClientRect();
          return { w: Math.round(r.width), h: Math.round(r.height),
                   vw: window.innerWidth, vh: window.innerHeight };
        })()`,
        returnByValue: true,
      }, sessionId);
      const { w: pw, h: ph, vw, vh } = cov.value;
      if (pw < vw - 1 || ph < vh - 1) {
        problems.push(`${shot.id}: the page paints only ${pw}x${ph} of a ${vw}x${vh} ` +
          `viewport — the rest of the capture would be blank`);
        continue;
      }

      const { data } = await cdp.send("Page.captureScreenshot",
        { format: "png", captureBeyondViewport: false }, sessionId);
      const buf = Buffer.from(data, "base64");
      await writeFile(path.join(OUT, shot.file), buf);
      const h = shot.measured ?? shot.height;
      console.log(`${shot.file.padEnd(24)} ${shot.width * dpr}x${h * dpr}` +
        `${dpr !== 1 ? ` (${dpr}x)` : ""}${shot.measured ? " (fitted)" : ""}` +
        `  ${(buf.length / 1024).toFixed(0)} KB`);
    }
  } finally {
    await dispose();
  }

  if (problems.length) {
    console.error("\nShots that failed to set up:");
    for (const p of problems) console.error("  " + p);
    process.exitCode = 1;
  } else {
    console.log(`\nWrote to ${path.relative(ROOT, OUT)}/`);
  }
}

main().catch((e) => { console.error(e); process.exit(1); });
